sensors:
 - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
   point_cloud_topic: /camera/depth_registered/points
   max_range: 2
   frame_subsample: 5
   point_subsample: 5
   padding_scale: 1.2
   padding_offset: 0.07
   shape_padding: 0.07 # this paramter seems not to be used

   #publish the filtered cloud (not needed therefore commented out for performance sake)
   #filtered_cloud_topic: filtered_cloud
