sensors:
 - sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
   image_topic: /camera/depth_registered/image_raw
   queue_size: 1
   near_clipping_plane_distance: 0.4
   far_clipping_plane_distance: 1.7
   skip_vertical_pixels: 3
   skip_horizontal_pixels: 3
   shadow_threshold: 0.2
   padding_scale: 1.2
   padding_offset: 0.07
   #filtered_cloud_topic: filtered_cloud
